### ISSUE TITLE
Devcmd runner does not report exit code when underlying script fails

### ISSUE THREAD

**Issue by schierla** [XITASO/devcmd#21] opened 2021-02-13 15:03 UTC
When a devcmd script fails with a non-zero exit code, the corresponding "yarn devcmd" still returns exit code 0.

### Steps to reproduce:
1. Create a devcmd `test.ts` containing `process.exit(1)`
2. Run `yarn devcmd test && echo This should not be shown if the command fails`

### Observed behavior: 
`This should not be shown if the command fails` is written to the console.

### Expected behavior: 
No output, because the devcmd failed.

### Likely cause
The return value of `spwanSync` (including the status code) is ignored in `devcmd/from-cli`
https://github.com/XITASO/devcmd/blob/f25760d1092702cf88dedd43f9731a19dd7315fb/packages/devcmd/src/from-cli/index.ts#L86

**Comment by PatrickLehnerXI** [comment] 2021-02-15 07:45
Thanks for your great bug report!

This is certainly a problem. The cause is the same as #17, but the situation is somewhat different, so I'm not closing this as a dupe for now.

I'm not sure when I get around to fixing this, so if you could send a PR, I'd be very grateful! :)

**Closed as completed** 2021-04-20 15:44 UTC
